/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SsoSuccessGoogleImport } from './routes/sso/success/google'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SsoSuccessGoogleRoute = SsoSuccessGoogleImport.update({
  id: '/sso/success/google',
  path: '/sso/success/google',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/sso/success/google': {
      id: '/sso/success/google'
      path: '/sso/success/google'
      fullPath: '/sso/success/google'
      preLoaderRoute: typeof SsoSuccessGoogleImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sso/success/google': typeof SsoSuccessGoogleRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sso/success/google': typeof SsoSuccessGoogleRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/sso/success/google': typeof SsoSuccessGoogleRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sso/success/google'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sso/success/google'
  id: '__root__' | '/' | '/sso/success/google'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SsoSuccessGoogleRoute: typeof SsoSuccessGoogleRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SsoSuccessGoogleRoute: SsoSuccessGoogleRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/sso/success/google"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/sso/success/google": {
      "filePath": "sso/success/google.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
