/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProtectedIndexImport } from './routes/protected/index'
import { Route as ProtectedLayoutImport } from './routes/protected/_layout'
import { Route as ProtectedLayoutSocketImport } from './routes/protected/_layout/socket'
import { Route as ProtectedLayoutExampleImport } from './routes/protected/_layout/example'

// Create Virtual Routes

const ProtectedImport = createFileRoute('/protected')()

// Create/Update Routes

const ProtectedRoute = ProtectedImport.update({
  id: '/protected',
  path: '/protected',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedIndexRoute = ProtectedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedLayoutRoute = ProtectedLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedLayoutSocketRoute = ProtectedLayoutSocketImport.update({
  id: '/socket',
  path: '/socket',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedLayoutExampleRoute = ProtectedLayoutExampleImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/protected': {
      id: '/protected'
      path: '/protected'
      fullPath: '/protected'
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/protected/_layout': {
      id: '/protected/_layout'
      path: '/protected'
      fullPath: '/protected'
      preLoaderRoute: typeof ProtectedLayoutImport
      parentRoute: typeof ProtectedRoute
    }
    '/protected/': {
      id: '/protected/'
      path: '/'
      fullPath: '/protected/'
      preLoaderRoute: typeof ProtectedIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/protected/_layout/example': {
      id: '/protected/_layout/example'
      path: '/example'
      fullPath: '/protected/example'
      preLoaderRoute: typeof ProtectedLayoutExampleImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/protected/_layout/socket': {
      id: '/protected/_layout/socket'
      path: '/socket'
      fullPath: '/protected/socket'
      preLoaderRoute: typeof ProtectedLayoutSocketImport
      parentRoute: typeof ProtectedLayoutImport
    }
  }
}

// Create and export the route tree

interface ProtectedLayoutRouteChildren {
  ProtectedLayoutExampleRoute: typeof ProtectedLayoutExampleRoute
  ProtectedLayoutSocketRoute: typeof ProtectedLayoutSocketRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedLayoutExampleRoute: ProtectedLayoutExampleRoute,
  ProtectedLayoutSocketRoute: ProtectedLayoutSocketRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/protected': typeof ProtectedLayoutRouteWithChildren
  '/protected/': typeof ProtectedIndexRoute
  '/protected/example': typeof ProtectedLayoutExampleRoute
  '/protected/socket': typeof ProtectedLayoutSocketRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/protected': typeof ProtectedIndexRoute
  '/protected/example': typeof ProtectedLayoutExampleRoute
  '/protected/socket': typeof ProtectedLayoutSocketRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/protected': typeof ProtectedRouteWithChildren
  '/protected/_layout': typeof ProtectedLayoutRouteWithChildren
  '/protected/': typeof ProtectedIndexRoute
  '/protected/_layout/example': typeof ProtectedLayoutExampleRoute
  '/protected/_layout/socket': typeof ProtectedLayoutSocketRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/protected'
    | '/protected/'
    | '/protected/example'
    | '/protected/socket'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/protected' | '/protected/example' | '/protected/socket'
  id:
    | '__root__'
    | '/'
    | '/protected'
    | '/protected/_layout'
    | '/protected/'
    | '/protected/_layout/example'
    | '/protected/_layout/socket'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/protected"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/protected": {
      "filePath": "protected",
      "children": [
        "/protected/_layout",
        "/protected/"
      ]
    },
    "/protected/_layout": {
      "filePath": "protected/_layout.tsx",
      "parent": "/protected",
      "children": [
        "/protected/_layout/example",
        "/protected/_layout/socket"
      ]
    },
    "/protected/": {
      "filePath": "protected/index.tsx",
      "parent": "/protected"
    },
    "/protected/_layout/example": {
      "filePath": "protected/_layout/example.tsx",
      "parent": "/protected/_layout"
    },
    "/protected/_layout/socket": {
      "filePath": "protected/_layout/socket.tsx",
      "parent": "/protected/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
